### ISSUE TITLE
Add information to describe message. 

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka.nrepl#17]
See https://github.com/nrepl/nrepl/issues/181#issuecomment-637403456

For babashka we should add to describe:

``` clojure
{:versions {:babashka "0.1.0"
            :babashka.nrepl "0.0.4"}}
```

**Comment by borkdude** [comment]
@retrogradeorbit This information is added to the describe message so CIDER knows that to expect from the runtime. How should we do this for bootleg, which is similar, but not the same as babashka, but also runs a babashka.nrepl server? 

@bbatsov Given that the babashka-ish CLIs are probably limited in amount, maybe for bootleg it would be ok to do:

```
{:versions {:bootleg "0.1.0"
            :babashka.nrepl "0.0.4"}}
```
so you can add a case switch for babashka, bootleg, etc?

**Comment by bbatsov** [comment]
Yeah, that's fine.
