### ISSUE TITLE
Implement pprint support

### ISSUE THREAD

**Issue by bbatsov** [babashka/babashka.nrepl#18]
That's pretty useful feature that allows clients to specify the way results would be printed. I'm guessing that getting this to work with babashka shouldn't be very hard. 

See https://nrepl.org/nrepl/0.7.0/design/middleware.html#_pretty_printing and https://github.com/nrepl/nrepl/blob/master/src/clojure/nrepl/middleware/print.clj for more details.

**Comment by kolharsam** [comment]
@borkdude could I get started with this before #27 perhaps? Once I'm perhaps comfortable with this, I could then jump to #27. Hope that is okay?

**Comment by borkdude** [comment]
@kolharsam Sounds good to me!

**Comment by borkdude** [comment]
@kolharsam Note that babashka patches clojure.pprint since the default one bloats the binary with GraalVM a bit. The code for that is in `babashka.impl.pprint`. We just have to ensure that when this library is used with babashka, the `babashka.impl.pprint` namespace is loaded first. But we can see the effect of that in CI where binary size is printed.

**Comment by kolharsam** [comment]
@borkdude just to be clear: while introducing support for pprint middleware for this, I need to keep in mind to load `babashka.impl.pprint` first and then build on top of that?
It seems like I'm reiterating your point but just wanted to make sure if I understood this correctly

**Comment by borkdude** [comment]
@kolharsam We need to make sure that in babashka itself babashk.impl.pprint is loaded before babashka.nrepl.
I now checked `main.clj` and this is already the case:
```
   [babashka.impl.pprint :refer [pprint-namespace]]
   [babashka.impl.process :refer [process-namespace]]
   [babashka.impl.protocols :refer [protocols-namespace]]
   [babashka.impl.reify :refer [reify-opts]]
   [babashka.impl.repl :as repl]
   [babashka.impl.socket-repl :as socket-repl]
   [babashka.impl.test :as t]
   [babashka.impl.tools.cli :refer [tools-cli-namespace]]
   [babashka.nrepl.server :as nrepl-server]
```
So I think we're good.

**Comment by borkdude** [comment]
All working now. Thanks @kolharsam, @Grazfather and @bbatsov!
