### ISSUE TITLE
name completion doesn't work for fully qualified names

### ISSUE THREAD

**Issue by retrogradeorbit** [babashka/babashka.nrepl#2]
name completion does work when you are in the namespace in question:

```clojure
user> (ns clojure.tools.cli)
nil
clojure.tools.cli> pars<tab>
;; completes parse-opts
```

But not from another namespace

```clojure
clojure.tools.cli> (ns user)
nil
user> clojure.tools.cli/par<tab>
;; no match
```

**Comment by retrogradeorbit** [comment]
This might be normal behavior. If I require the namespace with an alias, the completion works:

```clojure
user> (require '[clojure.tools.cli :as cli])
nil
user> clojure.tools.cli/pa<tab>
;; completes parse-opts
```

but if I require it without an alias, it does not

```clojure
user> (ns clean)
nil
clean> (require '[clojure.tools.cli])
nil
clean> clojure.tools.cli/pa<tab>
;; no match
```

It may be a good idea to always try and complete fully qualified namespaces even if they aren't required, as then you can go:

```clojure
(require '[clojure.to<tab>
;; completes clojure.tools.cli
```

**Comment by retrogradeorbit** [comment]
the real clojure nrepl behaves like the following:

- all namespaces are completable at any time

```clojure
user> clojure.to<tab>
;; offers all available namespaces as a completion
```

- once the fully qualified namespace is entered and a / is written, all public names are completable

```clojure
user> (ns clean)
nil
clean> sci-nrepl.server/st<tab>
;; offers two names
```

- requiring with an alias adds the alias namespace to completions list

```clojure
clean> (require '[sci-nrepl.server :as srv])
nil
clean> srv/st<tab>
;; offers two names
```

**Comment by borkdude** [comment]
@retrogradeorbit I guess this issue is fixed?

**Comment by retrogradeorbit** [comment]
fixed
