### ISSUE TITLE
Error when completing (System/getProperty ..)

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka.nrepl#24]
```
#error {
 :cause No namespace: System found
 :via
 [{:type clojure.lang.ExceptionInfo
   :message No namespace: System found [at line 1, column 7]
   :data {:type :sci/error, :line 1, :column 7, :message No namespace: System found [at line 1, column 7]}
```

**Comment by kwrooijen** [comment]
When connecting with lein I get the following error. Probably related?

```sh 
lein repl :connect localhost:23456
Connecting to nREPL at localhost:23456
REPL-y 0.5.1, nREPL 
Clojure 1.10.3
: Could not resolve symbol: java.lang.System/getProperty user 
nil
Error loading namespace; falling back to user
nil
```

**Comment by benjamin-asdf** [comment]
```clojure
  (require '[sci.addons :as addons])

  (def opts (-> {:namespaces {'foo.bar {'x 1}}} addons/future))
  (def sci-ctx (sci/init opts))

  (require '[sci.impl.interop :as interop])

  (interop/resolve-class sci-ctx 'System)
  nil
  (interop/resolve-class sci-ctx 'Object)
  java.lang.Object
```

I came this far. I when I chek the sci context I see some raw classes. Maybe the fix involves fixing `System` there

**Comment by borkdude** [comment]
@benjamin-asdf The issue is not about `System`, the issue is that completions can fail when trying to complete an interop form.

**Comment by benjamin-asdf** [comment]
@borkdude my current thinking is that impl/server.clj should check if the prefix is a statis class and then return the static members of the class. I guess I can check how cider-nrepl is completing interop.

**Comment by borkdude** [comment]
Yes, something like that. I think the nbb completions might be doing this better, maybe it's also worth checking there.

**Comment by benjamin-asdf** [comment]
@borkdude yes you are right. In a running `bb` instance `System` is imported correctly. 
I fixed the error by doing this: 
```clojure ns-found? (sci/eval-string* ctx (format "(find-ns '%s)" query-ns))```

Added  2 functions 

`ns-imports->completions` similar to nbb version but uses clojure.reflect
`import-symbols->completions` this is so you get the completion for example for "Sys" -> "System". It just seems like the correct behaviour to me.

**Comment by benjamin-asdf** [comment]
I'm thinking about the code and I wonder if `import-symbols->completions` should not exist and 
```clojure
                from-current-ns (fully-qualified-syms ctx (sci/eval-string* ctx "(ns-name *ns*)"))
                from-current-ns (map (fn [sym]
                                       [(namespace sym) (name sym) :unqualified])
                                     from-current-ns)
```

this should somehow end up returning those class names.
