### ISSUE TITLE
cider-doc doesn't work?

### ISSUE THREAD

**Issue by j-cr** [babashka/babashka.nrepl#26]
```
M-x cider-doc str RET
cider-fallback-eval:info: Wrong type argument: char-or-string-p, nil

M-x cider-version RET
CIDER 0.26.0 (Nesebar)
```

**Comment by j-cr** [comment]
```
$ bb --version
babashka v0.1.3
```

**Comment by borkdude** [comment]
I'm getting this with CIDER 0.25.0snapshot:

![Screenshot 2020-08-13 at 22 04 03](https://user-images.githubusercontent.com/284934/90181580-fe616600-ddb0-11ea-829e-a3b980c59a89.png)

**Comment by borkdude** [comment]
Can confirm that this is broken with CIDER 0.27.0snapshot. cc @bbatsov

**Comment by bbatsov** [comment]
> cider-fallback-eval:info: Wrong type argument: char-or-string-p, nil

I'll take a look tomorrow. Might be a good idea to implement the new `lookup` op, though.

**Comment by j-cr** [comment]
seems like this might be related:
https://github.com/clojure-emacs/cider/commit/4fd24b1e767c776ca9fe913121ecc55abe103c67

cider-fallback-eval:info -> (format cider-info-form var) ->

      (do
        (require 'clojure.java.io)
        (require 'clojure.walk)

        (if-let [var (resolve 'str)]
          (let [info (meta var)]
            (-> info
                (update :ns str)
                (update :name str)
                (update :file (comp str clojure.java.io/resource))
                (cond-> (:macro m) (update :macro str))
                (cond-> (:special-form m) (update :special-form str))
                (assoc :arglists-str (str (:arglists info)))
                (clojure.walk/stringify-keys)))))

->

`clojure.lang.ExceptionInfo: Could not resolve symbol: m [at line 11, column 27]`

**Comment by bbatsov** [comment]
Yeah, exactly. Seems like I pasted some code from Orchard and forgot to adjust it. Sorry about that!

**Comment by j-cr** [comment]
(fixed in master)
