### ISSUE TITLE
Implement new nREPL lookup op

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka.nrepl#27]

**Comment by kolharsam** [comment]
Hey @borkdude, could you provide more context on this?

**Comment by borkdude** [comment]
@kolharsam Hi! I don't know a lot about this, but this was a request that came from the nREPL project. Possibly @bozhidar knows more.

I found some docs here: https://nrepl.org/nrepl/ops.html#lookup

In general it's best if you look at example messages sent back and forth using this:

https://docs.cider.mx/cider/troubleshooting.html#debugging-the-communication-with-nrepl

and then try to implement that.

**Comment by kolharsam** [comment]
@bbatsov could you provide some context on this?

**Comment by bbatsov** [comment]
It's the op editors are supposed by default to resolve a symbol to a var and procure its definition location metadata (amongst others) https://nrepl.org/nrepl/ops.html#lookup

I think everything you need is here https://github.com/nrepl/nrepl/commit/6291c2ecfc104c19af76d79a3a20fb08c159e97d

**Comment by borkdude** [comment]
@bbatsov We don't need more context on the operation, that's pretty clear. But there is one open question here about something CIDER-specific:

https://github.com/babashka/babashka.nrepl/pull/33#issuecomment-741672378

**Comment by borkdude** [comment]
I believe this is now implemented in 0.0.4
