### ISSUE TITLE
stderr not sent back to client

### ISSUE THREAD

**Issue by tzzh** [babashka/babashka.nrepl#28]
When running `bb --nrepl-server` and the connecting to it with a nrpel client for example`lein repl :connect 1667`, stderr is not visible in the client, for example the following doesn't print anything
```
user=> (binding [*out* *err*]
    #_=>   (println "Hello, STDERR!"))
nil
```

**Comment by borkdude** [comment]
Hey @tzzh, thanks for the issue. We have tests for normal output here:

https://github.com/babashka/babashka.nrepl/blob/master/test/babashka/nrepl/server_test.clj#L213-L230

It should not be too hard to support the same for `:err` probably.

**Comment by tzzh** [comment]
Hey, so I realised when running this code that `sci/err` is not bound but I am not sure how to bind out the right writer.
Basically I am getting
``` clojure
#error {
 :cause class sci.impl.vars.SciUnbound cannot be cast to class java.io.Writer (sci.impl.vars.SciUnbound is in unnamed module of loader 'app'; java.io.Writer is in module java.base of loader 'bootstrap')
 :via
 [{:type clojure.lang.ExceptionInfo
   :message class sci.impl.vars.SciUnbound cannot be cast to class java.io.Writer (sci.impl.vars.SciUnbound is in unnamed module of loader 'app'; java.io.Writer is in module java.base of loader 'bootstrap') [at line 1, column 1]
   :data {:type :sci/error, :line 1, :column 1, :message class sci.impl.vars.SciUnbound cannot be cast to class java.io.Writer (sci.impl.vars.SciUnbound is in unnamed module of loader 'app'; java.io.Writer is in module java.base of loader 'bootstrap') [at line 1, column 1]}
```
so then in
https://github.com/babashka/babashka.nrepl/blob/3e97bcb289d4ed3072019354b7d3e6c513eed2e8/src/babashka/nrepl/impl/server.clj#L31-L32
I am not sure how to get the right print writer I tried `sci/err pw` but then it sends stderr to stdout and I am not sure how I can bind `sci/err` to the right writer

**Comment by borkdude** [comment]
@tzzh I think you need to build another replying-print-writer that sends "err" messages instead of "out" messages:

https://github.com/babashka/babashka.nrepl/blob/3e97bcb289d4ed3072019354b7d3e6c513eed2e8/src/babashka/nrepl/impl/utils.clj#L40

and bind that to `sci/err`.

I think it's nicer to make `"out"` and `"err"` pluggable as an argument.
Note that the original nREPL also does this:

https://github.com/nrepl/nrepl/blob/1cc9baae631703c184894559a2232275dc50dff6/src/clojure/nrepl/middleware/print.clj#L115

**Comment by tzzh** [comment]
OK cool I am not super familiar with the nrepl code but I am starting to understand thanks 👍 - I'll try and make a PR for this

**Comment by borkdude** [comment]
@tzzh The pod protocol was largely inspired by nREPL so you're probably more familiar than you realize :).

**Comment by borkdude** [comment]
Thanks!
