### ISSUE TITLE
Printing in lazy-evaluated code sends output to babashka process instead of the nrepl client

### ISSUE THREAD

**Issue by llacom** [babashka/babashka.nrepl#36]
It seems I stumbled upon a bug: when using babashka as an nrepl server, printing something will correctly send the output to the nrepl client, however printing something inside something lazy-evaluated will instead send the result to babashka process itself:

```
user=> (mapv (fn [x] (println "It works" x) (inc x)) [10 20])
It works 10
It works 20
[11 21]
user=> (map (fn [x] (println "It prints in babashka process" x) (inc x)) [10 20])
(11 21)
```

![image](https://user-images.githubusercontent.com/3349476/107736631-83681080-6d3d-11eb-9cac-84ecc22bf278.png)

Tested with
```
`--> bb --version
babashka v0.2.10
```

**Comment by borkdude** [comment]
@bbatsov Could you point me to how this is handled in nrepl/nrepl? Do you change the root binding of `*out*`, or do you force lazy sequences before sending?

**Comment by bbatsov** [comment]
I think the relevant code starts here https://github.com/nrepl/nrepl/blob/master/src/clojure/nrepl/middleware/interruptible_eval.clj#L81 There's no special handling for lazy sequences, but we do rebind the output streams in the evaluation logic.

**Comment by bbatsov** [comment]
I think the relevant code starts here https://github.com/nrepl/nrepl/blob/master/src/clojure/nrepl/middleware/interruptible_eval.clj#L81 There's no special handling for lazy sequences, but we do rebind the output streams in the evaluation logic.

**Comment by borkdude** [comment]
Fixed.
