### ISSUE TITLE
Errors lack context, maybe we can enhance them?

### ISSUE THREAD

**Issue by Olical** [babashka/babashka.nrepl#40]
Hey there, a bug was raised against Conjure (https://github.com/Olical/conjure/issues/206) detailing how errors in babashka lack most of the important information required for debugging when talking to babashka over an nREPL connection. The output when in the regular stdio prompt contains everything you need, so it's not the error, it's more about what the nREPL module decides to send back over the connection.

In the aforementioned issue you can see that the only nREPL message we get back from the server contains `"clojure.lang.ExceptionInfo: \n"`, after having a look at the source I can see that this is where the `:cause` of the error would probably go, which is `nil` in this case. https://github.com/babashka/babashka.nrepl/blob/d9b63bbadce04799ef791c02a7066dd3197aa1b9/src/babashka/nrepl/impl/utils.clj#L21-L30

Do you think it'd be possible to integrate the rich error formatting used in the stdio REPL over nREPL? Or would that be really hard to access and reuse? Because I think keeping consistent stderr output between nREPL and stdio will be the best way to go for predictable behaviour from the end user's perspective.

I'm happy to try and have a go at this at some point, just wanted to get some input on direction first.

Thanks a lot for all of your wonderful work!

**Comment by borkdude** [comment]
@Olical I'm open to receive improvements in this area but I have no concrete ideas how to solve this myself at this point. I'd have to look into it, but I'd be happy if you would do this as well. The idea is to stay close to the original implementation of nREPL for Clojure on the JVM.

**Comment by borkdude** [comment]
Improved the error for `(nth [] 3)` now.
