### ISSUE TITLE
Emacs Cider "Lisp Expression:" prompt when switching projects

### ISSUE THREAD

**Issue by kwrooijen** [babashka/babashka.nrepl#50]
## Issue
Bit of a weird bug, and not sure if this issue should be posted here but this doesn't happen with regular Clojure+Cider. When connecting to the nrepl everything seems to work fine, but when I switch to another project Emacs keep prompting "Lisp Expression:" in the minibuffer.

## Setup

Minimal Emacs config (Only install clojure + cider)
``` emacs-lisp
(setq gc-cons-threshold most-positive-fixnum)
(defvar bootstrap-version)

(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)

(use-package clojure-mode :straight t)

(use-package cider :straight t)
```

Minimal babashka nrepl setup:
```clojure
(ns nrepl-test.core
  (:require
   [sci.core :as sci]
   [sci.addons :as addons]
   [babashka.nrepl.server])
  (:gen-class))

(defn start-server! []
  (let [opts {:namespaces {'clojure.main {'repl-requires '[]}}}
        sci-ctx (-> (sci/init opts)
                    addons/future)]
    (babashka.nrepl.server/start-server! sci-ctx {:host "127.0.0.1" :port 23456})))

(defn -main [& args]
  (start-server!)
  @(promise))
```

## Steps to reproduce
1. Start the repl server with `lein run`
2. navigate with emacs to any Clojure project
3. M-x cider-connect >> localhost >> 23456
4. Eval some stuff (this works)
5. Navigate to another clojure project and open a clj file >> `Lisp expression:` should pop up

**Comment by borkdude** [comment]
I don't know enough about CIDER to say if this is a bug in our nREPL implementation or in CIDER or if it has anything to do with nREPL at all. I recommend checking at the respective projects.

**Comment by kwrooijen** [comment]
The reason this is probably breaking (next to Cider not having a safety net for this case) is because `System.getProperty` isn't implemented yet. See https://github.com/babashka/babashka.nrepl/issues/24

Cider issue:
https://github.com/clojure-emacs/cider/issues/3182

**Comment by borkdude** [comment]
#24 is only about completions, does that affect this issue?

**Comment by kwrooijen** [comment]
Oh my bad, I thought it was about it not being implemented. Now that I think about it, babashka.nrepl probably requires you to implement it yourself.
``` clojure
{:namespaces {'System {'getProperty (fn [v] (System/getProperty v))}}
```

Then no, it's not related. If users have to implement this themselves, maybe we should update the README for this bug?

**Comment by borkdude** [comment]
@kwrooijen The proper way to do this is `{:classes {'java.lang.System System} :imports {'System 'java.lang.System}}`. If this is required for CIDER, I would say this is on CIDER. An nREPL implementation should imo just adhere to the nREPL spec and not implement other editor-specific stuff to work normally.
