### ISSUE TITLE
`classpath` op may be undescribed

### ISSUE THREAD

**Issue by vemv** [babashka/babashka.nrepl#68]
Hi!

I tried bb latest today.

Within a CIDER repl connected to bb:

* `(nrepl-op-supported-p "eval" (current-buffer))` returns truthy
* `(nrepl-op-supported-p "classpath" (current-buffer))` returns nil

This means that CIDER won't be able to use the op.

Sounds like some descriptor was forgotten?

Thanks - V

**Comment by borkdude** [comment]
That's right, sorry about that.
