### ISSUE TITLE
`ns-list` op

### ISSUE THREAD

**Issue by vemv** [babashka/babashka.nrepl#69]
The ns-list op allows CIDER's "session linking" logic to function optimally. It probably is low-hanging fruit.

Here is a sample session for JVM clojure:

```
(-->
  id              "8"
  op              "ns-list"
  session         "fd96025c-22f1-4a28-80ee-c45f0edb7c43"
  time-stamp      "2023-09-28 21:46:04.939275000"
  exclude-regexps ("^cider.nrepl" "^refactor-nrepl" "^nrepl")
)
(<--
  id         "8"
  session    "fd96025c-22f1-4a28-80ee-c45f0edb7c43"
  time-stamp "2023-09-28 21:46:05.381198000"
  ns-list    ("babashka.fs" "cheshire.core" "cheshire.factory" "cheshire.generate" "cheshire.generate-seq" ,,,)
  status     ("done")
)

```

And here is its definition: https://github.com/clojure-emacs/cider-nrepl/blob/d39c735405a1e8fdc9c18dc9c0aa3efcc9d9f05f/src/cider/nrepl/middleware/ns.clj#L138

Thanks - V

**Comment by borkdude** [comment]
Seems simple enough indeed!

**Comment by vemv** [comment]
Awesome 🍻
